"""modify column type

Revision ID: 04c0d9fd8075
Revises: c4ca5f222a8c
Create Date: 2023-07-02 17:57:40.418319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '04c0d9fd8075'
down_revision = 'c4ca5f222a8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('picture',
               existing_type=mysql.VARCHAR(length=21),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'default.jpeg'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('picture',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=21),
               existing_nullable=False,
               existing_server_default=sa.text("'default.jpeg'"))

    # ### end Alembic commands ###
