"""Added default for category

Revision ID: 61ec34992f95
Revises: 3e3101a99647
Create Date: 2023-07-06 00:33:28.276085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '61ec34992f95'
down_revision = '3e3101a99647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.alter_column('category',
                              existing_type=mysql.VARCHAR(length=60),
                              type_=sa.String(length=50),
                              existing_nullable=True,
                              server_default='Miscellaneous')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.alter_column('category',
                              existing_type=sa.String(length=50),
                              type_=mysql.VARCHAR(length=60),
                              existing_nullable=True)

    # ### end Alembic commands ###
