"""idan

Revision ID: ac33e6fc1fb5
Revises: 77d9ad215e4d
Create Date: 2023-07-14 17:50:31.011327

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac33e6fc1fb5'
down_revision = '77d9ad215e4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('verification_code',
               existing_type=mysql.VARCHAR(length=6),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('verification_code',
               existing_type=mysql.VARCHAR(length=6),
               nullable=False)

    # ### end Alembic commands ###
