"""Changed length of picture column

Revision ID: b112f85fe256
Revises: fda9276a6487
Create Date: 2023-07-05 10:05:45.062673

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b112f85fe256'
down_revision = 'fda9276a6487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('picture',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=128),
               existing_nullable=False,
               existing_server_default=sa.text("'default.jpeg'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('picture',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'default.jpeg'"))

    # ### end Alembic commands ###
