"""empty message

Revision ID: c4ca5f222a8c
Revises: e50001094db1
Create Date: 2023-07-02 17:56:29.021284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4ca5f222a8c'
down_revision = 'e50001094db1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('picture',
                              existing_type=mysql.VARCHAR(length=20),
                              type_=sa.String(length=21),
                              existing_nullable=False,
                              existing_server_default=sa.text("'default.jpeg'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('picture',
                              existing_type=sa.String(length=21),
                              type_=mysql.VARCHAR(length=20),
                              existing_nullable=False,
                              existing_server_default=sa.text("'default.jpg'"))

    # ### end Alembic commands ###
