"""idan

Revision ID: c97b4058bbb9
Revises: ac33e6fc1fb5
Create Date: 2023-07-14 17:53:03.436019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c97b4058bbb9'
down_revision = 'ac33e6fc1fb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('verification_code',
               existing_type=mysql.VARCHAR(length=6),
               type_=sa.String(length=60),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('verification_code',
               existing_type=sa.String(length=60),
               type_=mysql.VARCHAR(length=6),
               existing_nullable=True)

    # ### end Alembic commands ###
