"""i dont know

Revision ID: cfaec915bd1c
Revises: 
Create Date: 2023-07-10 18:18:03.482419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cfaec915bd1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subheading', sa.Text(), nullable=True))
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=60),
               type_=sa.String(length=50),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('picture',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('picture',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)

    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=60),
               nullable=False)
        batch_op.drop_column('subheading')

    # ### end Alembic commands ###
