"""Modify column type

Revision ID: e50001094db1
Revises: 
Create Date: 2023-07-02 11:16:45.133891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e50001094db1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('picture',
                              existing_type=mysql.VARCHAR(length=20),
                              nullable=False,
                              server_default='default.jpeg')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('picture',
                              existing_type=mysql.VARCHAR(length=128),
                              nullable=True)

    # ### end Alembic commands ###
