"""Modified Posts table

Revision ID: fda9276a6487
Revises: e9d54fc45d5b
Create Date: 2023-07-05 00:17:59.472466

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fda9276a6487'
down_revision = 'e9d54fc45d5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.alter_column('picture',
                              existing_type=mysql.VARCHAR(length=256),
                              nullable=True,
                              server_default='default_post.jpg')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.alter_column('picture',
                              existing_type=mysql.VARCHAR(length=256),
                              nullable=True)

    # ### end Alembic commands ###
